# Generated by Django 2.0.9 on 2018-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181029_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_post.png', upload_to='post_pictures'),
        ),
    ]
